### PR TITLE
Match php5 and php7 version-specific interpreters.

### PR DESCRIPTION
**Pull request by joewreschnig**

### CODE REVIEW

**Comment by zonuexe** [comment]
@joewreschnig 
Nice. But, I think `"php\\(?:-?[3457]\\(\\.[0-9]+\\)*\\)?\\'"` is better.

Test case:

```el
(let ((pattern "php\\(?:-?[3457]\\(\\.[0-9]+\\)*\\)?\\'"))
  (cl-loop for f in '("php" "php4"  "php5" "php7" "php7.1" "php7.0.18"
                      "php-5" "php-7.1" "php-7.0.18")
           always (string-match-p pattern f)))
```

**Comment by joewreschnig** [comment]
I'm ambivalent as long as it matches `php`, `php5`, and `php7.0`. I haven't ever seen the hyphen in the real world, but my experience is 99% on Debian.

The `\\'` at the end is redundant. `interpreter-mode-alist` already anchors the pattern to the start and end of the matched executable. ("If \\\\`REGEXP\\\\' matches the name...")

**Comment by zonuexe** [comment]
@joewreschnig 
Oh... I missed [that line](https://github.com/emacs-mirror/emacs/blob/65eee8392ff95f58f7b0bd036e1fe065523658c6/lisp/files.el#L2897) and it is redundant as you said.

**Comment by joewreschnig** [comment]
Sorry, my elisp is a little rusty and I've never used ert before, so I'm at a loss for why my new tests fail. They seem to pass on my system (25.1, OS X), both interactively with `M-x ert` and with `make test`. Maybe there's some timing issue?

**Comment by ejmr** [comment]
> I haven't ever seen the hyphen in the real world, but my experience is 99% on Debian, and I don't think it could hurt anything.

I have.  **Rarely**.  But I have seen it on systems with multiple installations of different versions of PHP; I've even done it myself and had `php-5` vs `php-5.2` vs `php-7` and so on.  In my opinion we should account for the hyphen, as it's not any real extra effort in order to cover that tiny, one-percent chance use-case that someone *may* run into at some time or another.

**Comment by ejmr** [comment]
> ...I'm at a loss for why my new tests fail.

Your test (357) passes on my system.  The two which fail---27 and 200---fail in `master`, most likely meaning I introduced a regression some time ago.  A session of `git bisect` would be very useful for tracking down the problems and seeing why those tests fail, but that's a separate issue.

**Comment by joewreschnig** [comment]
If you're OK with the test sometimes failing on Travis I'm OK with merging as it stands.

It's such a limited change that if the tests keep failing for mysterious reasons, it might be better to remove the tests.

**Comment by ejmr** [comment]
@joewreschnig Merged.

My apologies for the long delay on this merge; I've been in and out of the hospital recently so thank you for your patience and continued work.

**Comment by scfc** [comment]
I've finally tracked down the Travis CI failures: `interpreter-mode-alist`'s members can only be regular expressions since Emacs 24.4 (http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=1af4c2203ce7954c089133234ba80e6272ce9458).  In prior versions, `interpreter-mode-alist`'s members were simple strings.  That the failures are not limited to `EMACS_VERSION=emacs-24.3-bin`, but also occur for `EMACS_VERSION=emacs-25.1-bin` and `EMACS_VERSION=emacs-snapshot` is due to the latter two not being able to install those versions, silently failing (`… || true` in `.travis.yml`), and then running the tests against the (default) GNU Emacs 24.3.1 (cf. https://travis-ci.org/ejmr/php-mode/jobs/271077930 and https://travis-ci.org/ejmr/php-mode/jobs/271077931).

I'll submit a PR that adds a compatibility shim for Emacs < 24.4.

**Pull request merged**
