### PR TITLE
Move php-current-* functions into php-mode.el

### PR DESCRIPTION
**Pull request by zonuexe**
There is no change in function, but the `php-current.el` file has been deleted.  This function does not depend on skeleton.

This function is merged in https://github.com/ejmr/php-mode/pull/323 , but I think the skeleton framework was inappropriate for this function.

`skeleton` works fine while entering statements with no successor.  However, in the middle of the sentence, `skeleton` outputs unnecessary line feeds.

php-mode-skeleton-is-bad

Therefore, I think it rational to abandon `skeleton` and use `insert`.
In addition, as a side effect of this change the problem https://github.com/ejmr/php-mode/issues/359 in the @bowenchen6 environment will be solved.

### CODE REVIEW

**Comment by ejmr** [comment]
@bowenchen6 Please let me know if these patches correct the problem for you.  If they do not then I will most likely merge the pull-request you submitted.

**Comment by ejmr** [comment]
And thank you for your patience over this admittedly simple bug.  I have been busy with "Real Life" stuff.

**Comment by bowenchen6** [comment]
ok

**Comment by ejmr** [comment]
I merged this branch in 9f24c8541f2fb19c965a35ed8c6634933dd7439c so read the merge commit message for some more information.

Thank you @bowenchen6 for reporting the bug and helping discuss solutions, and thank you @zonuexe for implementing this fix.

**Pull request merged**
