### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by sergeyklay**

### CODE REVIEW

**Comment by sergeyklay** [comment]
@ejmr Could you please take a look

**Comment by sergeyklay** [comment]
You're welcome

**Comment by ejmr** [comment]
> What happened with tests?

I'm sorry but I am not sure what you are asking.  Although I am extremely tired and about to go to sleep, so I could easily be misunderstanding a very simple question, and if so I apologize.

**Comment by sergeyklay** [comment]
The tests have failed. I mean the Travis CI builds. For example `EMACS_VERSION=emacs-24.3-bin`:
```
Ran 52 tests, 51 results as expected, 1 unexpected (2017-07-28 08:12:46+0000)
1 expected failures
1 unexpected results:
   FAILED  php-mode-test-issue-357
make: *** [test] Error 1
```

**Comment by zonuexe** [comment]
It seems that [travis-ci](https://travis-ci.org/ejmr/php-mode) and PR are not linked.

**Comment by ejmr** [comment]
Oh---that.  Thanks for pointing it out, since I clearly overlooked it.  There is no way on Earth a docstring typo broke that unit test.  I will look into it tomorrow after a full night's sleep, because if I tried to fix it now I would just end up breaking three other tests probably, lol.

**Pull request merged**
