### PR TITLE
Add defgroup :tag and fix comment style

### PR DESCRIPTION
**Pull request by zonuexe**
This change is for trivial aesthetic.

### CODE REVIEW

**Comment by ejmr** [comment]
When I use the branch `make test` fails on `php-mode-test-issue-200`.

**Comment by zonuexe** [comment]
@ejmr Thank you for reviewing!  I chose a safe way.

**Comment by ejmr** [comment]
@zonuexe Thanks!  I'll re-review and merge the branch tomorrow---going to sleep, lol---unless @syohex reviews and merges it first.

**Comment by syohex** [comment]
Looks good.

**Comment by syohex** [comment]
Merged

**Comment by ejmr** [comment]
Thanks!

**Comment by ejmr** [comment]
@zonuexe One suggestion for the future:

The branch contained a commit (7abb8bb) followed by a commit to revert it (a0530f6).  In the future I recommend forcibly removing the initial commit and re-doing the work; that way there is no need for a `git revert` and it creates less "clutter" in the history of `git log` output and such.  For example, you could have used `git reset --hard 973c4fe` to reset the files to the commit just before 7abb8bb, and then could have redone the changes and made a new commit, probably needed to use `git push --force` later to overwrite the new commit.

Anyway, not a big deal to me, just a small suggestion.  Thanks again for all your recent contributions.

**Comment by zonuexe** [comment]
@ejmr Thanks for your suggestion.

I generally like `rebase` (and` commit - fixup`) and `push - f`. (I frequently use it in other PR.)
I thought about keeping this trial and error in commit log.

But there is no big reason there, so I will do that from the next 👍

**Pull request merged**
