### PR TITLE
Fix chained method indentation for PSR2 style

### PR DESCRIPTION
**Pull request by syohex**
This is related to #237.
@krzysztof-magosa Could you check [this version](https://raw.githubusercontent.com/ejmr/php-mode/a551255444b48cebb96b96e5273cde4ee86ee803/php-mode.el) ?

#### Original

before

#### With this patch

after

### CODE REVIEW

**Comment by ejmr** [comment]
Alternatively, could we address #237 by modifying the definition of the PSR-2 style?  I.e. something like:

```lisp
(c-add-style
  "psr2"
  '("php"
    (c-offsets-alist . ((statement-cont . +)))))
```

We might also have to change the default value for `topmost-intro-cont`, but if changing the C-style settings would have the same effect then I think it would be preferable, as it would keep as much PSR-2--related code in the same place instead of having some style-specific logic for a lineup function that we use in multiple styles.

**Comment by syohex** [comment]
> Alternatively, could we address #237 by modifying the definition of the PSR-2 style?

Thanks for information.  I'll fix.

**Comment by syohex** [comment]
Done

**Comment by ejmr** [comment]
Great, thanks!

**Comment by trashofmasters** [comment]
:+1: thanks @syohex

**Comment by krzysztof-magosa** [comment]
Great job guys, many thanks :)

**Pull request merged**
