### PR TITLE
PHP 7.0 Syntax

### PR DESCRIPTION
**Pull request by ejmr**
I am working on a few patches to add support for some new syntax that is part of PHP 7.0, now that the first alpha is available.  Additional things I want to add before merging this is support for the new `??` operator and group namespace declarations.  I would also appreciate it if anyone double-checks these patches for errors before I merge anything.

### CODE REVIEW

**Comment by syohex** [comment]
Looks good.

**Comment by periklis** [comment]
:+1:

**Comment by trashofmasters** [comment]
Thanks for working on this @ejmr. 

To be fair I didn't test this out but the changes proposed so far don't seem like they would break anything.

**Comment by ejmr** [comment]
[Useful information for anyone who wants to help with anything related to PHP 7 support](https://github.com/tpunt/PHP7-Reference).

**Comment by ejmr** [comment]
I would like to merge this branch soon but I'd like for @syohex, @trashofmasters and anyone else interested to please double-check the functionality changes first.

**Comment by syohex** [comment]
Will do.

**Comment by ejmr** [comment]
Thank you!

**Comment by syohex** [comment]
Looks good :+1:.

**Comment by ejmr** [comment]
Thanks!  I'll merge it soon then.

**Pull request merged**
