### PR TITLE
fix some font-lock and indentation issues in emacs 25

### PR DESCRIPTION
**Pull request by fallchildren**
- Removed advice "font-lock-fontify-keywords-region" (fixes GitHub Issue: #280)
- Changed syntax-propertize code to work with emacs 25 (fixes GitHub Issue: #371)
- Necessary code changes to replace the advice (font-locking for namespaces)

### CODE REVIEW

**Comment by fallchildren** [comment]
Any idea why "php-heredoc-start-re" is not definied? Can't get the batch-byte-compile to work when using it in "syntax-propertize-rules".

**Comment by fallchildren** [comment]
For me it seems this has also fixed Github Issue: #390. Tested with current git master and Emacs 24.4.1.

**Comment by zonuexe** [comment]
@fallchildren Thanks for your contribution!
I will take some time to review it, so please wait a while.

**Comment by zonuexe** [comment]
@fallchildren Thanks!
I merged this patch to the master. I am worried that this change will destroy someone's environment, but we would like to wait for more feedback from users.

Please wait for a while to release this change as a stable version.

**Comment by fallchildren** [comment]
@zonuexe Cool stuff, thank!
I hope it does not. I've been using it productively for a week or so and it did not break anything for me "yet". My experience so far is that it is more stable for emacs25 and master. But who knows. If there are any problems, feel free to contact me.

**Pull request merged**
